### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FYXX** [wondervictor/WESPE.pytorch#4]
I downloaded the DPED dataset and run you code, but I got 

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 24, in main
    denoiseGAN = DenoiseGAN(config, cuda=args.use_cuda, training=not args.infer)
  File "/home/scw4750/LJC/DenoiseGAN/model.py", line 162, in __init__
    self.vgg = VGG()
  File "/home/scw4750/LJC/DenoiseGAN/model.py", line 108, in __init__
    self.mean = torch.Tensor([123.68,  116.779,  103.939]).to(self.model.device)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'device'

Then,  I try to delete the code ".to(self.model.device)", but also have a series of errors.
How do I solve it?

**Comment by FYXX** [comment]
I delete the code ".to(self.model.device)" and do not use the vgg loss, then I got 

UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/home/scw4750/LJC/DenoiseGAN/model.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.out(x))
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 43, in main
    loss = denoiseGAN.train_step(x, y)
  File "/home/scw4750/LJC/DenoiseGAN/model.py", line 224, in train_step
    y_fake_gray_dt_pred = self.discriminator_t(y_fake_gray)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/scw4750/LJC/DenoiseGAN/model.py", line 97, in forward
    x = self.conv_layers(x)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/scw4750/anaconda3/envs/research/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [48, 3, 11, 11], but got input of size [32, 100, 100] instead

**Comment by wondervictor** [comment]
OK，I'll fix it soon

**Comment by wondervictor** [comment]
fixed!
